### PR TITLE
Add SIG Chinese Localization proposal

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by tequilarista** [comment]
We still don't have APAC friendly times for the TOC meeting, arg.  In the meantime is there a way for a representative to attend a TOC meeting?

**Comment by LinuxSuRen** [comment]
@tequilarista Thanks for the response. I'd love to be there if this proposal to be putted in a specific agenda.

**Comment by tequilarista** [comment]
Sorry, missed your response! We have a calendar where you can see where when the meetings are -- every two weeks.  I will also revisit the idea of APAC friendly time slots for the TOC meeting to try make this easier.

**Comment by tequilarista** [comment]
We're going to switch to a friendlier time schedule, so the meeting on May 19 will be at 6PM PST or 9am Beijing time.  It would be great if you could join then?

**Comment by LinuxSuRen** [comment]
I'd love to join the meeting.

**Comment by tequilarista** [comment]
May 20, 9am.

Agenda: https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit?ts=5c9580be

Zoom link: https://zoom.us/my/cdf.toc

**Comment by tequilarista** [comment]
I realized I'm assuming you have VPN access?

**Comment by LinuxSuRen** [comment]
> alized I'm assuming you have VPN acce

No worries, I have it.

**Comment by donaldliu** [comment]
@LinuxSuRen 
May 19 at 6PM PST (Pacific Time) which is 9am May 20 in Beijing.

**Comment by LinuxSuRen** [comment]
@donaldliu Thanks for clarification.

**Comment by dlorenc** [comment]
We discussed last week in the TOC meeting. Takeaways were:

- The TOC thinks this effort is valuable for the CDF and it's projects
- It sounds like slightly more than just localization is in scope - things like social media presence were also mentioned

Next step is for @LinuxSuRen to fill out the standard proposal, including the other activities, then we can call a vote.

**Comment by LinuxSuRen** [comment]
@dlorenc Got it. I'm just kind of busy on my company's business. But I'll try my best to do it as soon as possible. Anyway, thanks for your reminding.

**Comment by LinuxSuRen** [comment]
Hi team, sorry about not responding for a long time. I stuck due to some changes in me. I am still willing to push this forward. Like @dlorenc mentioned this potential SIG can do more things, not just localization for documents. We also can do more things like project promotion localization.

For the social media part, I already did some work. For example, promote the translation blogs.

If I understand correctly, I need to fill out the standard proposal which described from [here](https://github.com/cdfoundation/toc/blob/master/GROUPS.md#creation-1). Right?

**Comment by majinghe** [comment]
Hi @dlorenc , I am Mike, an IBMer who focus on Coud Native DevOps. I am also interested in the proposal from @LinuxSuRen .   I think there are more things we can do in China about Cloud Native Continuous delivery, such meetup, summit to share  more CDF projects to other organization.

**Comment by afrittoli** [comment]
> Hi team, sorry about not responding for a long time. I stuck due to some changes in me. I am still willing to push this forward. Like @dlorenc mentioned this potential SIG can do more things, not just localization for documents. We also can do more things like project promotion localization.
> 
> For the social media part, I already did some work. For example, promote the translation blogs.
> 
> If I understand correctly, I need to fill out the standard proposal which described from [here](https://github.com/cdfoundation/toc/blob/master/GROUPS.md#creation-1). Right?

@LinuxSuRen are you still interested in pursuing this?

**Comment by LinuxSuRen** [comment]
@afrittoli Sure!!!

**Comment by oleg-nenashev** [comment]
I suggest polling other members before starting it. The idea is definitely
good. At the same time, would be nice to have more founding members when we
start

**Comment by LinuxSuRen** [comment]
hi @oleg-nenashev, thanks for your feedback on this. I've talked with some people privately. I'll invite them to leave their comments here.

**Comment by oleg-nenashev** [comment]
I am on vacation now, but I will try asking a few people when I am back.
Note that there are big CDF member companies like Huawei

**Comment by majinghe** [comment]
Hi @LinuxSuRen @oleg-nenashev , this is really a good news, the more people from different companies, the more interesting will be in the future.  I will try my best to ask other people who focused on this topic. If possible, we can schedule a meeting to push this thing forward.

**Comment by addozhang** [comment]
> Hi @LinuxSuRen @oleg-nenashev , this is really a good news, the more people from different companies, the more interesting will be in the future. I will try my best to ask other people who focused on this topic. If possible, we can schedule a meeting to push this thing forward.

Totally agree. I am in and hope to contribute.

**Review by oleg-nenashev — APPROVED** [review]
+1 for merging taking the responses

**Comment by fdegir** [comment]
I believe we need a SIG proposal together with a sponsor in order for us to vote on this.

Here are the links to SIG process and the proposal for the latest approved SIG as example.

Process: https://github.com/cdfoundation/toc/blob/master/GROUPS.md#sigs
Example: https://github.com/cdfoundation/toc/pull/91

**Comment by LinuxSuRen** [comment]
hi @fdegir , thanks for your reminder. I've added the proposal. Please feel free to check it from [here](https://github.com/cdfoundation/toc/pull/75/files#diff-bc794435a6acc5fff64aac223fd806c477cc00c66457e687c5080ba86a61aab6R1).

> I need to say sorry to all reviewers. I need to force push the git commits due to I messed up the commit history.

**Comment by JohnNiang** [comment]
**+1**. I am in and hope to contribute.

**Comment by LinuxSuRen** [comment]
> **+1**. I am in and hope to contribute.

So glad to have you. I'll put you on the member list.

**Comment by liangyuanpeng** [comment]
It definitely makes sense and  i hope to contribute.

**Comment by yuezhuangshi** [comment]
Hi all, I am Jasper from Zhongyuan Bank and focus on Cloud Native Devops. I am interested in this things and hoping to contribute.

**Comment by oleg-nenashev** [comment]
Let's officially sign it off at the next TOC meeting on Tuesday

**Review by oleg-nenashev — APPROVED** [review]
Added the topic to the TOC agenda.
Binding +1 from me taking the responses we've got.
Maybe the SIG could be merged with the Jenkins Chinese localization SIG

https://docs.google.com/document/d/1uBHar55fTInWF9Li4t0lyG3tTC8BRLU0FfBfsgk_Jrs/edit?ts=5c9580be#heading=h.isp7qhtdm7dr

**Comment by LinuxSuRen** [comment]
> Maybe the SIG could be merged with the Jenkins Chinese localization SIG

Good point. The Jenkins Chinese localization SIG can be part of this one.

**Comment by dlorenc** [comment]
+1 binding

**Comment by imjasonh** [comment]
+1 from me

**Comment by fdegir** [comment]
+1 binding

**Comment by mjmckay** [comment]
+1 binding

**Comment by dlorenc** [comment]
Bound! This is official!

**Comment by sbtaylor15** [comment]
a little late but +1 binding

**Comment by LinuxSuRen** [comment]
Thanks all of you. Thanks for the support from CDF members. And I believe that all the SIG members will promote CDF projects better.

**Comment by LinuxSuRen** [comment]
hi TOC team, please help us with the onboarding checklist https://github.com/cdfoundation/toc/issues/102. Thanks!

By the way, this is the kickoff meeting of this SIG. See also [the meeting notes](https://docs.google.com/document/d/14DtzBpOVHWpxXnx113slf6QaKG8qPLhx5M15ucNWsV8/edit?usp=sharing).

**Pull request merged**
