### PR TITLE
Jenkins Operator proposal

### PR DESCRIPTION
**Pull request by antoniaklja**
We are more than happy to be part of the CD.Foundation :)

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Please start a discussion in the TOC mailing list. Taking the response from @imjasonh, there is definitely no consensus. I will likely have to abstain on my own from voting. 

Requesting changes to prevent merge

**Comment by antoniaklja** [comment]
Sure, thank you @oleg-nenashev 👍

**Comment by antoniaklja** [comment]
I'm closing this PR as didn't get any response.

**Comment by imjasonh** [comment]
Sorry for not being more transparent with this discussion. The topic was discussed at the [August 17th TOC meeting](https://www.youtube.com/watch?v=OUwEAobwgQU).

Please feel free to reopen this issue or reopen the discussion on the mailing list if you feel there's more to discuss.

**Pull request closed without merging**
