### PR TITLE
Project Pyrsia proposal to CDF

### PR DESCRIPTION
**Pull request by betarelease**
Here is a proposal for Project Pyrsia to be accepted as part of the CDF. Please review the proposal and leave comments in the PR.

### CODE REVIEW

**Review by r2liquibase — APPROVED** [review]

**Comment by r2liquibase** [comment]
After viewing the presentations and chatting with the Pyrsia team, I am more convinced than before that this is absolutely the direction CDF needs to explore. Delivery doesn't matter if what you are delivering is dangerous.

**Comment by afrittoli** [comment]
Thank you for this thorough proposal. 
The project seems to me to be aligned to the CDF charter as a component that enables best practices for continues delivery.
From the CDF charter:

> a) The purpose of the Foundation is to raise, budget and spend funds in support of various continuous delivery open source and standards projects, including infrastructure and support initiatives related thereto (each such project, a "Technical Project"). The governance of each Technical Project is as set forth in the applicable charter for each Technical Project.

**Comment by joshgav** [comment]
+1 nb

Interesting to see CDF considering conventions for artifact and package management, that's an area ripe for rationalization. Relatedly there was a [PackagingCon](https://packaging-con.org/talks.html) in November sponsored by [NumFOCUS](https://numfocus.org/) which brought together lots of players in the package management ecosystem, that may provide some momentum.

**Review by oleg-nenashev — APPROVED** [review]
As the TOC voted, Project Pyrsia was accepted to the CDF as incubating project. I will go ahead and merge this proposal

I created https://github.com/cdfoundation/foundation/issues/406 to initiate the official project onboarding

**Pull request merged**
